/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_COMMA = 2,
  anon_sym_RBRACE = 3,
  anon_sym_COLON = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_DQUOTE = 7,
  anon_sym_DQUOTE2 = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_SQUOTE2 = 10,
  anon_sym_LBRACE2 = 11,
  sym__string_text = 12,
  sym__single_string_text = 13,
  sym_escape_sequence = 14,
  anon_sym_LBRACE_LBRACE = 15,
  anon_sym_RBRACE_RBRACE = 16,
  sym_token_name = 17,
  anon_sym_PIPE = 18,
  anon_sym_EQ = 19,
  sym_token_filter_name = 20,
  sym_token_text = 21,
  sym_number = 22,
  sym_true = 23,
  sym_false = 24,
  sym_null = 25,
  sym_comment = 26,
  sym_document = 27,
  sym__value = 28,
  sym_object = 29,
  sym_pair = 30,
  sym_array = 31,
  sym_string = 32,
  sym_string_content = 33,
  aux_sym__single_string_content = 34,
  sym_token = 35,
  sym_token_input = 36,
  sym_token_filter = 37,
  aux_sym_document_repeat1 = 38,
  aux_sym_object_repeat1 = 39,
  aux_sym_array_repeat1 = 40,
  aux_sym_string_content_repeat1 = 41,
  aux_sym_token_repeat1 = 42,
  aux_sym_token_input_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_SQUOTE2] = "'",
  [anon_sym_LBRACE2] = "{",
  [sym__string_text] = "_string_text",
  [sym__single_string_text] = "_single_string_text",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_token_name] = "token_name",
  [anon_sym_PIPE] = "|",
  [anon_sym_EQ] = "=",
  [sym_token_filter_name] = "token_filter_name",
  [sym_token_text] = "token_text",
  [sym_number] = "number",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_pair] = "pair",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [aux_sym__single_string_content] = "_single_string_content",
  [sym_token] = "token",
  [sym_token_input] = "token_input",
  [sym_token_filter] = "token_filter",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_content_repeat1] = "string_content_repeat1",
  [aux_sym_token_repeat1] = "token_repeat1",
  [aux_sym_token_input_repeat1] = "token_input_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [anon_sym_LBRACE2] = anon_sym_LBRACE,
  [sym__string_text] = sym__string_text,
  [sym__single_string_text] = sym__single_string_text,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_token_name] = sym_token_name,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_token_filter_name] = sym_token_filter_name,
  [sym_token_text] = sym_token_text,
  [sym_number] = sym_number,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_pair] = sym_pair,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [aux_sym__single_string_content] = aux_sym__single_string_content,
  [sym_token] = sym_token,
  [sym_token_input] = sym_token_input,
  [sym_token_filter] = sym_token_filter,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_content_repeat1] = aux_sym_string_content_repeat1,
  [aux_sym_token_repeat1] = aux_sym_token_repeat1,
  [aux_sym_token_input_repeat1] = aux_sym_token_input_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE2] = {
    .visible = true,
    .named = false,
  },
  [sym__string_text] = {
    .visible = false,
    .named = true,
  },
  [sym__single_string_text] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_token_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_token_filter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_token_text] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__single_string_content] = {
    .visible = false,
    .named = false,
  },
  [sym_token] = {
    .visible = true,
    .named = true,
  },
  [sym_token_input] = {
    .visible = true,
    .named = true,
  },
  [sym_token_filter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_token_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_token_input_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_filter = 1,
  field_input = 2,
  field_key = 3,
  field_name = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_filter] = "filter",
  [field_input] = "input",
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_filter, 0},
  [4] =
    {field_filter, 2, .inherited = true},
    {field_name, 1},
  [6] =
    {field_filter, 0, .inherited = true},
    {field_filter, 1, .inherited = true},
  [8] =
    {field_input, 3},
    {field_name, 1},
  [10] =
    {field_filter, 4, .inherited = true},
    {field_input, 3},
    {field_name, 1},
  [13] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_string_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__single_string_content, 2,
    aux_sym__single_string_content,
    sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 32,
  [35] = 32,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 37,
  [43] = 36,
  [44] = 44,
  [45] = 40,
  [46] = 39,
  [47] = 36,
  [48] = 44,
  [49] = 49,
  [50] = 40,
  [51] = 39,
  [52] = 44,
  [53] = 49,
  [54] = 37,
  [55] = 49,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 56,
  [61] = 61,
  [62] = 57,
  [63] = 58,
  [64] = 56,
  [65] = 58,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 75,
  [77] = 75,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 47,
        '\'', 49,
        ',', 41,
        '-', 29,
        '/', 4,
        ':', 43,
        '=', 70,
        '[', 44,
        '\\', 22,
        ']', 45,
        'f', 14,
        'n', 24,
        't', 20,
        '{', 50,
        '|', 69,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '=') ADVANCE(70);
      if (lookahead == '|') ADVANCE(69);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(54);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(60);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '"' ||
          lookahead == ',' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 8:
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(69);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == 0xfeff) ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(77);
      END_STATE();
    case 9:
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(69);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == 0xfeff) ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(77);
      END_STATE();
    case 10:
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == 0xfeff) ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == 0xfeff) ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '=') ADVANCE(70);
      if (lookahead == '|') ADVANCE(69);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == '{') ADVANCE(65);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(66);
      END_STATE();
    case 27:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(63);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 35:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 46,
        '\'', 48,
        ',', 41,
        '-', 29,
        '/', 4,
        ':', 43,
        '=', 70,
        '[', 44,
        ']', 45,
        'f', 14,
        'n', 24,
        't', 20,
        '{', 40,
        '|', 69,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 46,
        '\'', 48,
        ',', 41,
        '-', 29,
        '/', 4,
        ':', 43,
        '[', 44,
        ']', 45,
        'f', 14,
        'n', 24,
        't', 20,
        '{', 39,
        '}', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) SKIP(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(65);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE2);
      if (lookahead == '{') ADVANCE(65);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead == '/') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__string_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead == '*') ADVANCE(59);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead == '/') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0xfeff) ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__single_string_text);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_token_name);
      if (lookahead == '/') ADVANCE(35);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_token_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_token_filter_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_token_text);
      if (lookahead == '*') ADVANCE(74);
      if (lookahead == '/') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_token_text);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '"' ||
          lookahead == ',' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_token_text);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '"' ||
          lookahead == ',' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_token_text);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(69);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == 0xfeff) ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_token_text);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == 0xfeff) ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_token_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != ',' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead == '"' ||
          lookahead == ',' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 37},
  [5] = {.lex_state = 37},
  [6] = {.lex_state = 37},
  [7] = {.lex_state = 37},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 37},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 37},
  [30] = {.lex_state = 37},
  [31] = {.lex_state = 37},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 37},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 13},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [anon_sym_LBRACE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(83),
    [sym__value] = STATE(2),
    [sym_object] = STATE(20),
    [sym_array] = STATE(20),
    [sym_string] = STATE(20),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [sym_true] = ACTIONS(15),
    [sym_false] = ACTIONS(15),
    [sym_null] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym__value,
      aux_sym_document_repeat1,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [34] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(24), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(30), 1,
      anon_sym_SQUOTE,
    STATE(3), 2,
      sym__value,
      aux_sym_document_repeat1,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(33), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [68] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(36), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym__value,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [101] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [120] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(40), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      sym__value,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [191] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(46), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym__value,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [278] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    STATE(79), 1,
      sym__value,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [380] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [398] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    STATE(78), 1,
      sym__value,
    STATE(20), 3,
      sym_object,
      sym_array,
      sym_string,
    ACTIONS(15), 4,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 12,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number,
      sym_true,
      sym_false,
      sym_null,
  [446] = 7,
    ACTIONS(66), 1,
      anon_sym_DQUOTE2,
    ACTIONS(68), 1,
      anon_sym_LBRACE2,
    ACTIONS(72), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(74), 1,
      sym_comment,
    STATE(84), 1,
      sym_string_content,
    ACTIONS(70), 2,
      sym__string_text,
      sym_escape_sequence,
    STATE(22), 2,
      sym_token,
      aux_sym_string_content_repeat1,
  [470] = 6,
    ACTIONS(72), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_DQUOTE2,
    ACTIONS(78), 1,
      anon_sym_LBRACE2,
    ACTIONS(80), 2,
      sym__string_text,
      sym_escape_sequence,
    STATE(25), 2,
      sym_token,
      aux_sym_string_content_repeat1,
  [491] = 7,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_SQUOTE2,
    ACTIONS(84), 1,
      anon_sym_LBRACE2,
    ACTIONS(88), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(26), 1,
      aux_sym__single_string_content,
    STATE(38), 1,
      sym_token,
    ACTIONS(86), 2,
      sym__single_string_text,
      sym_escape_sequence,
  [514] = 7,
    ACTIONS(66), 1,
      anon_sym_SQUOTE2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LBRACE2,
    ACTIONS(88), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(23), 1,
      aux_sym__single_string_content,
    STATE(38), 1,
      sym_token,
    ACTIONS(86), 2,
      sym__single_string_text,
      sym_escape_sequence,
  [537] = 6,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_DQUOTE2,
    ACTIONS(92), 1,
      anon_sym_LBRACE2,
    ACTIONS(98), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(95), 2,
      sym__string_text,
      sym_escape_sequence,
    STATE(25), 2,
      sym_token,
      aux_sym_string_content_repeat1,
  [558] = 7,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SQUOTE2,
    ACTIONS(103), 1,
      anon_sym_LBRACE2,
    ACTIONS(109), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(26), 1,
      aux_sym__single_string_content,
    STATE(38), 1,
      sym_token,
    ACTIONS(106), 2,
      sym__single_string_text,
      sym_escape_sequence,
  [581] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(112), 2,
      anon_sym_COMMA,
      sym_token_text,
    ACTIONS(116), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
    STATE(28), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [600] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(118), 2,
      anon_sym_COMMA,
      sym_token_text,
    ACTIONS(124), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
    STATE(28), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [619] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(128), 1,
      sym_number,
    STATE(80), 1,
      sym_pair,
    STATE(81), 1,
      sym_string,
  [641] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(128), 1,
      sym_number,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_pair,
    STATE(81), 1,
      sym_string,
  [663] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(128), 1,
      sym_number,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_pair,
    STATE(81), 1,
      sym_string,
  [685] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(58), 1,
      sym_token_input,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      sym_token_text,
    STATE(27), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [703] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(74), 1,
      sym_token_input,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      sym_token_text,
    STATE(27), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [721] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(65), 1,
      sym_token_input,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      sym_token_text,
    STATE(27), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [739] = 5,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(63), 1,
      sym_token_input,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      sym_token_text,
    STATE(27), 2,
      sym_token,
      aux_sym_token_input_repeat1,
  [757] = 2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(136), 5,
      anon_sym_COMMA,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
      sym_token_text,
  [768] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(140), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    STATE(60), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [787] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(144), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [800] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(148), 3,
      anon_sym_DQUOTE2,
      sym__string_text,
      sym_escape_sequence,
  [813] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(152), 3,
      anon_sym_DQUOTE2,
      sym__string_text,
      sym_escape_sequence,
  [826] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(128), 1,
      sym_number,
    STATE(80), 1,
      sym_pair,
    STATE(81), 1,
      sym_string,
  [845] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_COLON,
    ACTIONS(158), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(56), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [864] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(160), 3,
      anon_sym_DQUOTE2,
      sym__string_text,
      sym_escape_sequence,
  [877] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(162), 3,
      anon_sym_DQUOTE2,
      sym__string_text,
      sym_escape_sequence,
  [890] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(152), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [903] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(148), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [916] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(160), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [929] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(162), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [942] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(166), 3,
      anon_sym_SQUOTE2,
      sym__single_string_text,
      sym_escape_sequence,
  [955] = 2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(154), 5,
      anon_sym_COMMA,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
      sym_token_text,
  [966] = 2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(150), 5,
      anon_sym_COMMA,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
      sym_token_text,
  [977] = 2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(164), 5,
      anon_sym_COMMA,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
      sym_token_text,
  [988] = 2,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(168), 5,
      anon_sym_COMMA,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
      sym_token_text,
  [999] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(64), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1018] = 3,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_LBRACE2,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(166), 3,
      anon_sym_DQUOTE2,
      sym__string_text,
      sym_escape_sequence,
  [1031] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(174), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1047] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(176), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1063] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(178), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(57), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1079] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(180), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1095] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(182), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1111] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(186), 1,
      anon_sym_PIPE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1127] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(189), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1143] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(191), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(59), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1159] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(193), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(61), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1175] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(195), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(62), 1,
      aux_sym_token_repeat1,
    STATE(73), 1,
      sym_token_filter,
  [1191] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_repeat1,
  [1204] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_array_repeat1,
  [1217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_RBRACK,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_array_repeat1,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_object_repeat1,
  [1243] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_object_repeat1,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_EQ,
    ACTIONS(215), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
  [1267] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_repeat1,
  [1280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_PIPE,
  [1296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(229), 1,
      sym_token_name,
  [1306] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(233), 1,
      sym_token_name,
  [1316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(237), 1,
      sym_token_name,
  [1326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COLON,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_token_filter_name,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_DQUOTE2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 101,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 191,
  [SMALL_STATE(10)] = 224,
  [SMALL_STATE(11)] = 242,
  [SMALL_STATE(12)] = 260,
  [SMALL_STATE(13)] = 278,
  [SMALL_STATE(14)] = 308,
  [SMALL_STATE(15)] = 326,
  [SMALL_STATE(16)] = 344,
  [SMALL_STATE(17)] = 362,
  [SMALL_STATE(18)] = 380,
  [SMALL_STATE(19)] = 398,
  [SMALL_STATE(20)] = 428,
  [SMALL_STATE(21)] = 446,
  [SMALL_STATE(22)] = 470,
  [SMALL_STATE(23)] = 491,
  [SMALL_STATE(24)] = 514,
  [SMALL_STATE(25)] = 537,
  [SMALL_STATE(26)] = 558,
  [SMALL_STATE(27)] = 581,
  [SMALL_STATE(28)] = 600,
  [SMALL_STATE(29)] = 619,
  [SMALL_STATE(30)] = 641,
  [SMALL_STATE(31)] = 663,
  [SMALL_STATE(32)] = 685,
  [SMALL_STATE(33)] = 703,
  [SMALL_STATE(34)] = 721,
  [SMALL_STATE(35)] = 739,
  [SMALL_STATE(36)] = 757,
  [SMALL_STATE(37)] = 768,
  [SMALL_STATE(38)] = 787,
  [SMALL_STATE(39)] = 800,
  [SMALL_STATE(40)] = 813,
  [SMALL_STATE(41)] = 826,
  [SMALL_STATE(42)] = 845,
  [SMALL_STATE(43)] = 864,
  [SMALL_STATE(44)] = 877,
  [SMALL_STATE(45)] = 890,
  [SMALL_STATE(46)] = 903,
  [SMALL_STATE(47)] = 916,
  [SMALL_STATE(48)] = 929,
  [SMALL_STATE(49)] = 942,
  [SMALL_STATE(50)] = 955,
  [SMALL_STATE(51)] = 966,
  [SMALL_STATE(52)] = 977,
  [SMALL_STATE(53)] = 988,
  [SMALL_STATE(54)] = 999,
  [SMALL_STATE(55)] = 1018,
  [SMALL_STATE(56)] = 1031,
  [SMALL_STATE(57)] = 1047,
  [SMALL_STATE(58)] = 1063,
  [SMALL_STATE(59)] = 1079,
  [SMALL_STATE(60)] = 1095,
  [SMALL_STATE(61)] = 1111,
  [SMALL_STATE(62)] = 1127,
  [SMALL_STATE(63)] = 1143,
  [SMALL_STATE(64)] = 1159,
  [SMALL_STATE(65)] = 1175,
  [SMALL_STATE(66)] = 1191,
  [SMALL_STATE(67)] = 1204,
  [SMALL_STATE(68)] = 1217,
  [SMALL_STATE(69)] = 1230,
  [SMALL_STATE(70)] = 1243,
  [SMALL_STATE(71)] = 1256,
  [SMALL_STATE(72)] = 1267,
  [SMALL_STATE(73)] = 1280,
  [SMALL_STATE(74)] = 1288,
  [SMALL_STATE(75)] = 1296,
  [SMALL_STATE(76)] = 1306,
  [SMALL_STATE(77)] = 1316,
  [SMALL_STATE(78)] = 1326,
  [SMALL_STATE(79)] = 1334,
  [SMALL_STATE(80)] = 1342,
  [SMALL_STATE(81)] = 1350,
  [SMALL_STATE(82)] = 1357,
  [SMALL_STATE(83)] = 1364,
  [SMALL_STATE(84)] = 1371,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_content, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_content_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__single_string_content, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__single_string_content, 2, 0, 0), SHIFT_REPEAT(38),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_string_content, 2, 0, 0), SHIFT_REPEAT(38),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__single_string_content, 2, 0, 0), SHIFT_REPEAT(76),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token_input, 1, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_token_input_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_token_input_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_token_input_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 4, 0, 5),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__single_string_content, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__single_string_content, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 3, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 3, 0, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 4, 0, 5),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 5, 0, 7),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 5, 0, 7),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token, 6, 0, 8),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token, 6, 0, 8),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_token_repeat1, 2, 0, 6),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_token_repeat1, 2, 0, 6), SHIFT_REPEAT(82),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_filter, 2, 0, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_token_repeat1, 1, 0, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_filter, 4, 0, 9),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [245] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stardew_json(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
